## Numpy

In [4]:
# Her şey nesne olduğu için sayılar, listeler bir sürü fonksiyon özellik taşıyor
# Bu da kaynak tüketiyor
# Sadece aritmetik işlemler kullanmak için bu şekilde kaynak tüketmemek için bilimde kullanabilmek için numpy 

In [6]:
import numpy as np

### Array

- Hepsi aynı tür
- Daha az yer kaplıyor


In [7]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [8]:
array_a = np.array([1, 2, 3, 4])

In [9]:
array_b = np.array([0, .5, 1, 1.5])
array_b

array([0. , 0.5, 1. , 1.5])

In [10]:
array_a[0]

1

In [11]:
array_b[-1]

1.5

In [13]:
array_a[0:3]

array([1, 2, 3])

In [14]:
# Artık buna ulaşıp değiştrebiliriz int8 ' e ne kadar yer kaplayacağını değiştirebileceğiz sayı sınırlanırına göre 

array_a.dtype

dtype('int32')

In [16]:
array_b.dtype

dtype('float64')

In [17]:
empty_array = np.array([])

In [18]:
empty_array.dtype

dtype('float64')

In [19]:
np.array([0, .5, 1, 1.5], dtype=np.float_)

array([0. , 0.5, 1. , 1.5])

In [20]:
np.array([0, .5, 1, 1.5], dtype=np.int8)

array([0, 0, 1, 1], dtype=int8)

In [ ]:
## Numpy verininbüyüklüğü sabit ekledikçe büyümüyor pythondan farklı olarak

In [21]:
array_c = np.array(["ADA", "LOVELACE"])

In [22]:
array_c.dtype

dtype('<U8')

### Dimensions and shapes

In [24]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [1, 2, 3]

])

In [25]:
array_a.shape

(4,)

In [26]:
my_array.shape

(3, 3)

In [27]:
array_a.ndim

1

In [28]:
my_array.ndim

2

In [29]:
my_array.size

9

In [30]:
# Boyutların tutarlı olması gerekiyor her eleman aynı boyutta
my_array = np.array([
    [
        [12, 11, 10],
        [9, 8, 7]
    ],
    [
        [6, 5, 4],
        [3, 2, 1]

    ]

])

In [31]:
my_array.ndim

3

In [33]:
my_array.shape

(2, 2, 3)

In [34]:
my_array.size

12

### Indexing and Slicing

In [35]:
my_array = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [36]:
my_array[1]

array([4, 5, 6])

In [37]:
my_array[1][0]

4

In [38]:
my_array[1, 0]

4

In [39]:
my_array[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [40]:
my_array[:2, :2]

array([[1, 2],
       [4, 5]])

In [41]:
my_array[1] = np.array([10, 10, 10])

In [42]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [43]:
my_array[2] = 99

In [44]:
my_array

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [45]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [47]:
my_array = np.arange(1, 11)
my_array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [48]:
my_array.reshape(5, 2)

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10]])

In [49]:
np.arange(1, 10.1, 4)

array([1., 5., 9.])

In [54]:
np.zeros((2, 3, 7) )

array([[[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0.]]])

In [55]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [58]:
np.eye(5, 5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [62]:
my_array = np.random.random((5,2))
my_array

array([[0.276238  , 0.70867296],
       [0.75016877, 0.44707106],
       [0.64085702, 0.06893301],
       [0.80807069, 0.5860202 ],
       [0.39082511, 0.73219927]])

In [64]:
np.random.randint(100, size=(20,3))

array([[48, 16, 91],
       [69, 97, 10],
       [22, 77, 74],
       [12, 40, 48],
       [45, 69, 79],
       [21, 12, 22],
       [53, 54,  9],
       [31, 31,  9],
       [85, 74, 14],
       [ 8, 66, 90],
       [38, 96, 11],
       [80, 97, 63],
       [43, 22, 90],
       [57, 44, 81],
       [89, 23, 15],
       [70,  3, 59],
       [11, 13, 14],
       [44, 44, 64],
       [63,  7, 77],
       [72, 16, 52]])

In [69]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [ ]:
#any()
#all()
#full()
#concatenate()

In [70]:
np.any([1, 2, 3])

True

In [71]:
np.all([1,2,3])

True

In [73]:
array1 = np.arange(0, 10)
array1 = array1.reshape(2,5)
array1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [74]:
np.concatenate([array1, array1])

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [75]:
np.concatenate([array1, array1], axis = 1)

array([[0, 1, 2, 3, 4, 0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9, 5, 6, 7, 8, 9]])

## Statistics

In [77]:
array1 = np.arange(0, 10)
array1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [80]:
print(array1.sum())
print(array1.mean())
print(array1.std())
print(array1.var())

45
4.5
2.8722813232690143
8.25


In [82]:
array1.reshape(5, 2).sum(axis=1)

array([ 1,  5,  9, 13, 17])

In [83]:
array1 + 10

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [85]:
array1 += 10

In [86]:
array1

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

### Boolean Arrays

In [88]:
num_array = np.arange(4)
num_array

array([0, 1, 2, 3])

In [89]:
num_array[0], num_array[-1]

(0, 3)

In [90]:
num_array[[0,-1]]

array([0, 3])

In [92]:
num_array[[True, False, False, True]]

array([0, 3])

In [93]:
num_array >=2

array([False, False,  True,  True])

In [94]:
# İstediğininz şartları sağlayan verilere ulaşmak içn
#Filtreleme
num_array[num_array >=2 ]

array([2, 3])

In [95]:
num_array[num_array > num_array.mean()]

array([2, 3])

In [97]:
num_array[ (num_array == 0) | (num_array== 1)]

array([0, 1])

In [98]:
num_array[(num_array <= 2) & (num_array % 2 == 0)]

array([0, 2])

In [102]:
rand_array = np.random.randint(100, size=(3,3))
print(rand_array)
rand_array[ rand_array > 30 ]

[[10 30 10]
 [ 7 26 39]
 [39 33 18]]


array([39, 39, 33])

In [104]:
bool_array = rand_array > 30

In [105]:
bool_array

array([[False, False, False],
       [False, False,  True],
       [ True,  True, False]])

In [106]:
rand_array[bool_array]

array([39, 39, 33])

In [109]:
array_1= np.arange(0, 10).reshape(2,5)
array_2= np.arange(0, 10).reshape(5,2)

In [110]:
array_1

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [111]:
array_2

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [113]:
np.dot(array_2, array_1)

array([[  5,   6,   7,   8,   9],
       [ 15,  20,  25,  30,  35],
       [ 25,  34,  43,  52,  61],
       [ 35,  48,  61,  74,  87],
       [ 45,  62,  79,  96, 113]])

In [115]:
array_2.T

array([[0, 2, 4, 6, 8],
       [1, 3, 5, 7, 9]])

In [117]:
import sys

In [118]:
sys.getsizeof(10)

28

In [120]:
sys.getsizeof(1000**100)

160

In [121]:
np.dtype(int).itemsize

4

In [122]:
np.dtype(np.int8).itemsize

1

In [123]:
np.dtype(float).itemsize

8

In [124]:
sys.getsizeof([1, 2, 3])

80

In [135]:
sys.getsizeof(np.array([1, 2]))

104

In [126]:
np.array([1, 2, 3]).nbytes

12

In [127]:
my_list = list(range(100000))
my_array = np.arange(100000)

In [129]:
%time np.sum(my_array ** 2)

Wall time: 0 ns


285

In [130]:
%time np.sum(number ** 2 for number in my_list)

Wall time: 54.8 ms


<timed eval>:1: DeprecationWarning: Calling np.sum(generator) is deprecated, and in the future will give a different result. Use np.sum(np.fromiter(generator)) or the python sum builtin instead.


333328333350000